### ISSUE TITLE
If that possible to support a .gif file?

### ISSUE THREAD

**Issue by nlpsuge** [PRATAP-KUMAR/ActivitiesText#1]
Hi,
If that possible to support a .gif file?

**Comment by PRATAP-KUMAR** [comment]
Hi
Sorry for late reply.
I am trying for what you have mentioned.
Will get back soon.

**Comment by PRATAP-KUMAR** [comment]
Hi I have investigated the possibility and found no it's not possible. But if you have any logo with gif, I can try it only for that gif in another way without changing the present code of this extension.
