### ISSUE TITLE
Add option to prevent Right-click to open configurations

### ISSUE THREAD

**Issue by cantalisa** [PRATAP-KUMAR/ActivitiesText#2]
Hello, thank you very much for your extension, it is very useful to me.

I know that it is a quick option and it is convenient, and it is very useful to right-click the activities button to quickly open the extension settings and modify the values.

But. Could you add an option where this behavior is optional? I feel like it can be a little distracting

Thank you very much, regards

**Comment by PRATAP-KUMAR** [comment]
Hi, I am going through your comment. The normal behaviour, when this extension is not installed, when you right click is same as left click. Would you like to keep this behaviour or dont want any action? I am trying to edit the code, waiting for your reply.

**Comment by cantalisa** [comment]
Yes, please keep normal behavoir (right click is same as left click)!

**Comment by PRATAP-KUMAR** [comment]
Hi, Sorry for late reply. I have edited the code. There is still work to do. Right now I have done it for gnome-shell 40. What is your version of gnome-shell?

**Comment by cantalisa** [comment]
Don't Worry! Yes, I am using GNOME 40.4

**Comment by PRATAP-KUMAR** [comment]
Ok. I have uploaded it for review. It's approved. Restart gnome-shell now and see the change.

**Comment by cantalisa** [comment]
Thanks! It works pretty sweet. You're the best. Greetings, have a nice day.
